### ISSUE TITLE
Error installing library with new python

### ISSUE THREAD

**Issue by AlexPietrow** [ISP-SST/ISPy#59]
I updated my python and the new version does not accept ISPy to be installed. 
See error below. Any idea what the issue can be?

```
apietrow@airy://work1/apietrow/GoriaCLV/sdo> pip install git+https://github.com/ISP-SST/ISPy
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ISP-SST/ISPy
  Cloning https://github.com/ISP-SST/ISPy to /tmp/pip-req-build-2lrmhabn
  Running command git clone --filter=blob:none --quiet https://github.com/ISP-SST/ISPy /tmp/pip-req-build-2lrmhabn
  Resolved https://github.com/ISP-SST/ISPy to commit 5f3b67600a7094103c09ec6e475549180752743f
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j4tjix3h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j4tjix3h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-j4tjix3h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j4tjix3h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by cdiazbas** [comment]
This issue does not seems to be related with ISPy itself. The error message states that there is a ModuleNotFoundError for the numpy module, indicating that the numpy package is not installed or not available. To resolve this issue, you can try installing the numpy package separately before attempting to install the ISPy package.
